Running on sh05
# conda environments:
#
base                  *  /opt/conda
PGx_env                  /usr/users/rattrapagemehdibenghali/benghali_meh/.conda/envs/PGx_env
PGx_env_37               /usr/users/rattrapagemehdibenghali/benghali_meh/.conda/envs/PGx_env_37

Read cache from caches/data_facebook/bart-large_CADEC_word.pt.
max_len_a:1.6, max_len:10
In total 3 datasets:
	dev has 1097 instances.
	test has 1160 instances.
	train has 5340 instances.

The number of tokens in tokenizer  50265
50266 50271
Testing dataset info 

Testing dataset info 

+-------------+----------+-------------+-----------+--------------+------------+-------------+------------+-------+-------------+-------------+
| field_names | entities | entity_tags | raw_words | entity_spans | tgt_tokens | target_span | src_tokens | first | src_seq_len | tgt_seq_len |
+-------------+----------+-------------+-----------+--------------+------------+-------------+------------+-------+-------------+-------------+
|   is_input  |  False   |    False    |   False   |    False     |    True    |    False    |    True    |  True |     True    |     True    |
|  is_target  |   True   |    False    |   False   |    False     |    True    |     True    |   False    | False |    False    |     True    |
| ignore_type |   True   |             |           |              |   False    |     True    |   False    | False |    False    |    False    |
|  pad_value  |    0     |             |           |              |     1      |      0      |     1      |   0   |      0      |      0      |
+-------------+----------+-------------+-----------+--------------+------------+-------------+------------+-------+-------------+-------------+
Validation dataset info 

+-------------+----------+-------------+-----------+--------------+------------+-------------+------------+-------+-------------+-------------+
| field_names | entities | entity_tags | raw_words | entity_spans | tgt_tokens | target_span | src_tokens | first | src_seq_len | tgt_seq_len |
+-------------+----------+-------------+-----------+--------------+------------+-------------+------------+-------+-------------+-------------+
|   is_input  |  False   |    False    |   False   |    False     |    True    |    False    |    True    |  True |     True    |     True    |
|  is_target  |   True   |    False    |   False   |    False     |    True    |     True    |   False    | False |    False    |     True    |
| ignore_type |   True   |             |           |              |   False    |     True    |   False    | False |    False    |    False    |
|  pad_value  |    0     |             |           |              |     1      |      0      |     1      |   0   |      0      |      0      |
+-------------+----------+-------------+-----------+--------------+------------+-------------+------------+-------+-------------+-------------+

Traceback (most recent call last):
  File "./BARTNER/train.py", line 238, in <module>
    trainer = Trainer(train_data=ds, model=model, optimizer=optimizer,
  File "/usr/users/rattrapagemehdibenghali/benghali_meh/.local/lib/python3.8/site-packages/fastNLP/core/trainer.py", line 559, in __init__
    _check_code(dataset=train_data, model=self.model, losser=losser, forward_func=self._forward_func, metrics=metrics,
  File "/usr/users/rattrapagemehdibenghali/benghali_meh/.local/lib/python3.8/site-packages/fastNLP/core/trainer.py", line 959, in _check_code
    for batch_count, (batch_x, batch_y) in enumerate(_iter):
  File "/usr/users/rattrapagemehdibenghali/benghali_meh/.local/lib/python3.8/site-packages/fastNLP/core/batch.py", line 266, in __iter__
    for indices, batch_x, batch_y in self.dataiter:
  File "/usr/users/rattrapagemehdibenghali/benghali_meh/.conda/envs/PGx_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/usr/users/rattrapagemehdibenghali/benghali_meh/.conda/envs/PGx_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/users/rattrapagemehdibenghali/benghali_meh/.conda/envs/PGx_env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/users/rattrapagemehdibenghali/benghali_meh/.local/lib/python3.8/site-packages/fastNLP/core/batch.py", line 90, in collate_fn
    sin_y = _pad(sin_y, dataset=self.dataset, as_numpy=self.as_numpy)
  File "/usr/users/rattrapagemehdibenghali/benghali_meh/.local/lib/python3.8/site-packages/fastNLP/core/batch.py", line 43, in _pad
    res = f.pad(vlist)
  File "/usr/users/rattrapagemehdibenghali/benghali_meh/.local/lib/python3.8/site-packages/fastNLP/core/field.py", line 492, in pad
    return self.padder(contents, field_name=self.name, field_ele_dtype=self.dtype, dim=self._cell_ndim)
  File "/usr/users/rattrapagemehdibenghali/benghali_meh/.local/lib/python3.8/site-packages/fastNLP/core/field.py", line 247, in __call__
    return np.array(contents)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
