pre. tgt. for `dev`:   0%|          | 0/75 [00:00<?, ?it/s]pre. tgt. for `dev`:  63%|██████▎   | 47/75 [00:00<00:00, 469.00it/s]                                                                     pre. tgt. for `test`:   0%|          | 0/76 [00:00<?, ?it/s]pre. tgt. for `test`:  64%|██████▍   | 49/76 [00:00<00:00, 488.52it/s]                                                                      pre. tgt. for `train`:   0%|          | 0/567 [00:00<?, ?it/s]pre. tgt. for `train`:   9%|▊         | 49/567 [00:00<00:01, 483.22it/s]pre. tgt. for `train`:  18%|█▊        | 102/567 [00:00<00:00, 495.61it/s]pre. tgt. for `train`:  26%|██▋       | 150/567 [00:00<00:00, 489.21it/s]pre. tgt. for `train`:  36%|███▌      | 205/567 [00:00<00:00, 505.50it/s]pre. tgt. for `train`:  46%|████▌     | 259/567 [00:00<00:00, 514.15it/s]pre. tgt. for `train`:  54%|█████▍    | 309/567 [00:00<00:00, 508.52it/s]pre. tgt. for `train`:  64%|██████▍   | 362/567 [00:00<00:00, 511.50it/s]pre. tgt. for `train`:  74%|███████▎  | 417/567 [00:00<00:00, 519.47it/s]pre. tgt. for `train`:  83%|████████▎ | 469/567 [00:00<00:00, 517.12it/s]pre. tgt. for `train`:  92%|█████████▏| 519/567 [00:01<00:00, 505.71it/s]                                                                         Traceback (most recent call last):
  File "./BARTNER/train.py", line 324, in <module>
    trainer = Trainer(train_data=ds, model=model, optimizer=optimizer,
  File "/usr/users/rattrapagemehdibenghali/benghali_meh/.local/lib/python3.8/site-packages/fastNLP/core/trainer.py", line 523, in __init__
    self.model = _move_model_to_device(model, device=device)
  File "/usr/users/rattrapagemehdibenghali/benghali_meh/.local/lib/python3.8/site-packages/fastNLP/core/utils.py", line 430, in _move_model_to_device
    raise ValueError("There is no usable gpu. set `device` as `cpu` or `None`.")
ValueError: There is no usable gpu. set `device` as `cpu` or `None`.
